import { Eta } from "eta";
import type {
  HarnessId,
  HarnessSpec,
  McpEntry,
  SkillEntry,
  StackProfile,
} from "./schemas.js";

export interface GenerateInput {
  projectName: string;
  projectDescription: string;
  stack: StackProfile;
  harnesses: HarnessSpec[];
  skills: SkillEntry[];
  mcps: McpEntry[];
}

export interface GeneratedFile {
  path: string;
  content: string;
  harnessId?: HarnessId | "universal";
}

const eta = new Eta({
  autoEscape: false,
  autoTrim: false,
  varName: "it",
  useWith: false,
});

const TEMPLATES = {
  agents: `# <%= it.projectName %>

<%= it.projectDescription %>

## Stack

**<%= it.stack.name %>** — <%= it.stack.description %>

## Conventions

<% it.stack.conventions.forEach((c) => { %>- <%= c %>
<% }) %>

## Setup

\`\`\`bash
# Install dependencies, run dev server, run tests — fill in for this project.
\`\`\`

## Skills configured

<% if (it.skills.length === 0) { %>None.
<% } else { %><% it.skills.forEach((s) => { %>- **<%= s.name %>** — <%= s.description %> (<%= s.sourceUrl %>)
<% }) %><% } %>

## MCP servers configured

<% if (it.mcps.length === 0) { %>None.
<% } else { %><% it.mcps.forEach((m) => { %>- **<%= m.name %>** — <%= m.description %> (<%= m.sourceUrl %>)
<% }) %><% } %>

---
Generated by [AppBlueprints](https://github.com/philipposk/AppBlueprints).
`,

  claude: `# Claude Code Instructions — <%= it.projectName %>

<%= it.projectDescription %>

## Stack

<%= it.stack.name %>: <%= it.stack.description %>

## Conventions

<% it.stack.conventions.forEach((c) => { %>- <%= c %>
<% }) %>

## Skills

Installed skills live in \`~/.claude/skills/\` and \`.claude/skills/\` (project scope).
<% it.skills.forEach((s) => { %>- [\`<%= s.id %>\`](<%= s.sourceUrl %>) — <%= s.description %>
<% }) %>

## MCP servers

See \`.mcp.json\` for the active server list.
`,

  cursorRules: `---
description: "Project rules for <%= it.projectName %>"
alwaysApply: true
---

# <%= it.projectName %>

<%= it.projectDescription %>

## Conventions
<% it.stack.conventions.forEach((c) => { %>
- <%= c %><% }) %>
`,

  clineRules: `---
description: "<%= it.projectName %>"
---

# <%= it.projectName %>

<%= it.projectDescription %>

<% it.stack.conventions.forEach((c) => { %>- <%= c %>
<% }) %>
`,

  windsurfRules: `Project: <%= it.projectName %>
<%= it.projectDescription %>

Stack: <%= it.stack.name %>
<% it.stack.conventions.forEach((c) => { %>
- <%= c %><% }) %>
`,

  conventionsMd: `# Conventions — <%= it.projectName %>

<%= it.projectDescription %>

<% it.stack.conventions.forEach((c) => { %>- <%= c %>
<% }) %>
`,

  aiderConf: `# Generated by AppBlueprints
read:
  - CONVENTIONS.md
model: anthropic/claude-opus-4-20250514
auto-commits: false
`,

  continueYaml: `name: <%= it.projectName.toLowerCase().replace(/[^a-z0-9-]/g, "-") %>
version: 0.0.1
schema: v1
rules:
<% it.stack.conventions.forEach((c) => { %>  - "<%= c.replace(/"/g, '\\"') %>"
<% }) %>models:
  - name: Claude Opus
    provider: anthropic
    model: claude-opus-4-20250514
    roles: [chat, edit]
`,

  geminiMd: `# <%= it.projectName %>

<%= it.projectDescription %>

## Stack
<%= it.stack.name %>

## Conventions
<% it.stack.conventions.forEach((c) => { %>- <%= c %>
<% }) %>
`,

  zedRules: `# <%= it.projectName %>
<%= it.projectDescription %>

Stack: <%= it.stack.name %>

Conventions:
<% it.stack.conventions.forEach((c) => { %>- <%= c %>
<% }) %>
`,

  openhandsRepo: `---
name: repo-conventions
agent: CodeActAgent
---

# <%= it.projectName %>

<%= it.projectDescription %>

## Stack
<%= it.stack.name %>

## Conventions
<% it.stack.conventions.forEach((c) => { %>- <%= c %>
<% }) %>
`,

  todoMd: `# TODO — <%= it.projectName %>

Generated MVP task list. Edit freely.

## Setup
- [ ] Install dependencies (\`<%= it.stack.id.startsWith("fastapi") ? "uv sync" : it.stack.id === "rust-cli" ? "cargo build" : "pnpm install" %>\`)
- [ ] Configure secrets in \`.env\` (or \`.env.local\`)
- [ ] Run the dev server and confirm it boots

## Build
- [ ] Sketch the data model
- [ ] Build the smallest end-to-end happy path
- [ ] Wire up auth (if needed)
- [ ] Wire up storage (if needed)

## Quality
- [ ] First test that exercises the happy path
- [ ] CI: lint + typecheck + test on every PR
- [ ] Deploy preview environment

## Skills installed
<% it.skills.forEach((s) => { %>- [ ] Try the **<%= s.name %>** skill — <%= s.sourceUrl %>
<% }) %>
`,

  specMd: `# Spec — <%= it.projectName %>

## What this is
<%= it.projectDescription %>

## Stack
<%= it.stack.name %> — <%= it.stack.description %>

## Conventions
<% it.stack.conventions.forEach((c) => { %>- <%= c %>
<% }) %>

## Open questions
- [ ] (fill in)
- [ ] (fill in)

## Out of scope
- (fill in)
`,
};

function renderMcpJson(mcps: McpEntry[]): string {
  if (mcps.length === 0) {
    return JSON.stringify({ mcpServers: {} }, null, 2) + "\n";
  }

  const merged: Record<string, unknown> = {};
  for (const mcp of mcps) {
    try {
      const parsed = JSON.parse(mcp.configSnippet);
      Object.assign(merged, parsed);
    } catch {
      // Skip entries with malformed snippets; should not happen in seeded data.
    }
  }
  return JSON.stringify({ mcpServers: merged }, null, 2) + "\n";
}

export function generate(input: GenerateInput): GeneratedFile[] {
  const files: GeneratedFile[] = [];
  const ctx = {
    projectName: input.projectName,
    projectDescription: input.projectDescription,
    stack: input.stack,
    skills: input.skills,
    mcps: input.mcps,
  };

  const has = (id: HarnessId) => input.harnesses.some((h) => h.id === id);
  const anyAgentsMd = input.harnesses.some((h) => h.agentsMdCompatible);

  if (anyAgentsMd || input.harnesses.length === 0) {
    files.push({
      path: "AGENTS.md",
      content: eta.renderString(TEMPLATES.agents, ctx),
      harnessId: "universal",
    });
  }

  if (has("claude-code")) {
    files.push({
      path: "CLAUDE.md",
      content: eta.renderString(TEMPLATES.claude, ctx),
      harnessId: "claude-code",
    });
  }

  if (has("cursor")) {
    files.push({
      path: ".cursor/rules/main.mdc",
      content: eta.renderString(TEMPLATES.cursorRules, ctx),
      harnessId: "cursor",
    });
  }

  if (has("cline")) {
    files.push({
      path: ".clinerules/main.md",
      content: eta.renderString(TEMPLATES.clineRules, ctx),
      harnessId: "cline",
    });
  }

  if (has("windsurf")) {
    files.push({
      path: ".windsurfrules",
      content: eta.renderString(TEMPLATES.windsurfRules, ctx),
      harnessId: "windsurf",
    });
  }

  if (has("aider")) {
    files.push({
      path: "CONVENTIONS.md",
      content: eta.renderString(TEMPLATES.conventionsMd, ctx),
      harnessId: "aider",
    });
    files.push({
      path: ".aider.conf.yml",
      content: eta.renderString(TEMPLATES.aiderConf, ctx),
      harnessId: "aider",
    });
  }

  if (has("continue")) {
    files.push({
      path: ".continue/config.yaml",
      content: eta.renderString(TEMPLATES.continueYaml, ctx),
      harnessId: "continue",
    });
  }

  if (has("gemini-cli")) {
    files.push({
      path: "GEMINI.md",
      content: eta.renderString(TEMPLATES.geminiMd, ctx),
      harnessId: "gemini-cli",
    });
  }

  if (has("zed")) {
    files.push({
      path: ".rules",
      content: eta.renderString(TEMPLATES.zedRules, ctx),
      harnessId: "zed",
    });
  }

  if (has("openhands")) {
    files.push({
      path: ".openhands/microagents/repo.md",
      content: eta.renderString(TEMPLATES.openhandsRepo, ctx),
      harnessId: "openhands",
    });
  }

  const mcpEnabledHarness = input.harnesses.some((h) => h.supports.mcp);
  if (mcpEnabledHarness && input.mcps.length > 0) {
    files.push({
      path: ".mcp.json",
      content: renderMcpJson(input.mcps),
      harnessId: "universal",
    });
  }

  files.push({
    path: "TODO.md",
    content: eta.renderString(TEMPLATES.todoMd, ctx),
    harnessId: "universal",
  });

  files.push({
    path: "SPEC.md",
    content: eta.renderString(TEMPLATES.specMd, ctx),
    harnessId: "universal",
  });

  return files;
}
