#!/usr/bin/env node
// Generates AWESOME.md + JSON mirror from data/. Reads the built @appblueprints/core.
// Run with: pnpm build-awesome (after pnpm -r build).
import { mkdir, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { loadAll } from "../packages/core/dist/index.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, "..");
const dataDir = resolve(repoRoot, "data");
const outDir = resolve(repoRoot, "dist-awesome");

function header() {
  return `# Awesome AI-Dev Configs [![Awesome](https://awesome.re/badge.svg)](https://github.com/sindresorhus/awesome)

Curated configs, skills, and MCP servers for every popular AI coding tool. Auto-generated from [philipposk/AppBlueprints](https://github.com/philipposk/AppBlueprints) — \`data/\` is the source of truth.

## Contents

- [Harnesses](#harnesses)
- [Stacks](#stacks)
- [Skills](#skills)
- [MCP servers](#mcp-servers)

`;
}

function section(title, body) {
  return `## ${title}\n\n${body}\n`;
}

function harnessList(harnesses) {
  return harnesses
    .map((h) => {
      const flags = [];
      if (h.supports.skills) flags.push("skills");
      if (h.supports.mcp) flags.push("mcp");
      if (h.supports.memory) flags.push("memory");
      if (h.agentsMdCompatible) flags.push("AGENTS.md");
      const flagStr = flags.length ? ` _(${flags.join(", ")})_` : "";
      return `- [**${h.name}**](${h.docsUrl}) — ${h.vendor}.${flagStr}`;
    })
    .join("\n");
}

function stackList(stacks) {
  return stacks
    .map((s) => `- **${s.name}** (\`${s.id}\`) — ${s.description}`)
    .join("\n");
}

function skillList(skills) {
  const recommended = skills.filter((s) => s.recommended);
  const rest = skills.filter((s) => !s.recommended);
  const fmt = (s) =>
    `- [${s.name}](${s.sourceUrl}) — ${s.description}${
      s.stacks.length ? ` _(stacks: ${s.stacks.join(", ")})_` : ""
    }`;
  const blocks = [];
  if (recommended.length) {
    blocks.push(`### Recommended\n\n${recommended.map(fmt).join("\n")}\n`);
  }
  if (rest.length) {
    blocks.push(`### Firehose\n\n${rest.map(fmt).join("\n")}\n`);
  }
  return blocks.join("\n");
}

function mcpList(mcps) {
  const grouped = new Map();
  for (const m of mcps) {
    const tag = m.tags[0] ?? "other";
    if (!grouped.has(tag)) grouped.set(tag, []);
    grouped.get(tag).push(m);
  }
  const keys = [...grouped.keys()].sort();
  return keys
    .map((k) => {
      const list = grouped
        .get(k)
        .sort((a, b) => a.name.localeCompare(b.name))
        .map(
          (m) =>
            `- [${m.name}](${m.sourceUrl}) — ${m.description}${
              m.recommended ? " ⭐" : ""
            }`
        )
        .join("\n");
      return `### ${k}\n\n${list}\n`;
    })
    .join("\n");
}

async function main() {
  const { harnesses, skills, mcps, stacks } = await loadAll({ dataDir });

  const md =
    header() +
    section("Harnesses", harnessList(harnesses)) +
    section("Stacks", stackList(stacks)) +
    section("Skills", skillList(skills)) +
    section("MCP servers", mcpList(mcps)) +
    `\n---\n\nGenerated by \`scripts/build-awesome.mjs\`.\n`;

  const json = {
    generatedAt: new Date().toISOString(),
    harnesses,
    stacks,
    skills,
    mcps,
  };

  await mkdir(outDir, { recursive: true });
  await writeFile(resolve(outDir, "AWESOME.md"), md, "utf8");
  await writeFile(
    resolve(outDir, "appblueprints-data.json"),
    JSON.stringify(json, null, 2) + "\n",
    "utf8"
  );
  await writeFile(resolve(repoRoot, "AWESOME.md"), md, "utf8");

  console.log(
    `wrote ${outDir}/AWESOME.md (${md.length} bytes) + appblueprints-data.json (${JSON.stringify(json).length} bytes)`
  );
  console.log(`also wrote ${repoRoot}/AWESOME.md for repo display`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
