import { mkdir, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { stringify as stringifyYaml } from "yaml";
import { SOURCES } from "./sources.js";
import {
  extractMarkdownLinks,
  isGitHubRepoUrl,
  repoSlugFromUrl,
  type MarkdownLink,
} from "./parse.js";
import { loadExistingIds } from "./diff.js";

interface Candidate {
  id: string;
  name: string;
  description: string;
  sourceUrl: string;
  kind: "skill" | "mcp";
  origin: string;
}

interface CrawlOptions {
  dataDir: string;
  outDir: string;
  fetchImpl?: typeof fetch;
}

async function fetchText(url: string, impl: typeof fetch): Promise<string> {
  const res = await impl(url, {
    headers: { Accept: "text/plain, text/markdown, */*" },
  });
  if (!res.ok) {
    throw new Error(`Fetch failed (${res.status}): ${url}`);
  }
  return await res.text();
}

function toCandidate(
  link: MarkdownLink,
  kind: "skill" | "mcp",
  origin: string
): Candidate | null {
  if (!isGitHubRepoUrl(link.url)) return null;
  const id = `crawl-${repoSlugFromUrl(link.url)}`;
  return {
    id,
    name: link.name,
    description: link.description || `Discovered ${kind} from ${origin}`,
    sourceUrl: link.url,
    kind,
    origin,
  };
}

function toMcpYaml(c: Candidate) {
  return {
    id: c.id,
    name: c.name,
    description: c.description.slice(0, 240),
    sourceUrl: c.sourceUrl,
    transport: "stdio",
    auth: "none",
    tags: ["uncategorised"],
    stacks: [],
    recommended: false,
    configSnippet: `{}`,
  };
}

function toSkillYaml(c: Candidate) {
  return {
    id: c.id,
    name: c.name,
    description: c.description.slice(0, 240),
    sourceUrl: c.sourceUrl,
    tags: ["uncategorised"],
    stacks: [],
    harnesses: [],
    recommended: false,
  };
}

export async function crawl(opts: CrawlOptions): Promise<{
  newSkills: number;
  newMcps: number;
  writtenAt: string;
}> {
  const fetchImpl = opts.fetchImpl ?? fetch;
  const existingMcpIds = await loadExistingIds(opts.dataDir, "mcps");
  const existingSkillIds = await loadExistingIds(opts.dataDir, "skills");

  const candidates: Candidate[] = [];

  for (const src of SOURCES) {
    let body: string;
    try {
      body = await fetchText(src.rawUrl, fetchImpl);
    } catch (err) {
      console.warn(`[skip] ${src.id}: ${(err as Error).message}`);
      continue;
    }
    const links = extractMarkdownLinks(body);
    for (const link of links) {
      const cand = toCandidate(link, src.kind, src.name);
      if (cand) candidates.push(cand);
    }
  }

  const seen = new Set<string>();
  const newMcps: Candidate[] = [];
  const newSkills: Candidate[] = [];

  for (const c of candidates) {
    const dedupeKey = `${c.kind}:${c.id}`;
    if (seen.has(dedupeKey)) continue;
    seen.add(dedupeKey);

    const known =
      c.kind === "mcp"
        ? existingMcpIds.has(c.id) ||
          existingMcpIds.has(c.sourceUrl.toLowerCase())
        : existingSkillIds.has(c.id) ||
          existingSkillIds.has(c.sourceUrl.toLowerCase());
    if (known) continue;

    if (c.kind === "mcp") newMcps.push(c);
    else newSkills.push(c);
  }

  await mkdir(opts.outDir, { recursive: true });
  const writtenAt = new Date().toISOString();

  if (newMcps.length > 0) {
    const payload = newMcps.map(toMcpYaml);
    await writeFile(
      resolve(opts.outDir, "mcps.candidates.yml"),
      `# Auto-generated by crawler at ${writtenAt}.\n# Review, refine, then move into data/mcps/.\n\n${stringifyYaml(payload)}`,
      "utf8"
    );
  }

  if (newSkills.length > 0) {
    const payload = newSkills.map(toSkillYaml);
    await writeFile(
      resolve(opts.outDir, "skills.candidates.yml"),
      `# Auto-generated by crawler at ${writtenAt}.\n# Review, refine, then move into data/skills/.\n\n${stringifyYaml(payload)}`,
      "utf8"
    );
  }

  await writeFile(
    resolve(opts.outDir, "summary.json"),
    JSON.stringify(
      {
        writtenAt,
        sources: SOURCES.length,
        newMcps: newMcps.length,
        newSkills: newSkills.length,
        totalCandidates: candidates.length,
      },
      null,
      2
    ) + "\n",
    "utf8"
  );

  return { newSkills: newSkills.length, newMcps: newMcps.length, writtenAt };
}

const isMain = (() => {
  if (typeof process === "undefined" || !process.argv[1]) return false;
  return (
    resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url))
  );
})();

if (isMain) {
  const here = dirname(fileURLToPath(import.meta.url));
  const dataDir = resolve(here, "../../data");
  const outDir = resolve(here, "../out");
  console.log(`crawling into ${outDir}`);
  crawl({ dataDir, outDir })
    .then((r) => {
      console.log(
        `done — ${r.newMcps} new MCPs, ${r.newSkills} new skills at ${r.writtenAt}`
      );
    })
    .catch((err) => {
      console.error("crawler failed:", err);
      process.exit(1);
    });
}
